version: 0.0
os: linux
files:
  - source: /target/testCiCd.war
    destination: /usr/share/tomcat8/webapps
  - source: /configure_http_port.xsl
    destination: /usr/share/tomcat8/webapps

hooks:
BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
    - location: start_application
      timeout: 300
      runas: root
ApplicationStop:
    - location: stop_application
      timeout: 300
      runas: root
