version: 0.0
os: linux
files:
  - source: /target/testCiCd.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
permissions:
  - object: /opt/codedeploy-agent
    pattern: "**"
    mode: 755
hooks:
  ApplicationStop:
    - location: stop_application
      timeout: 300
  AfterInstall:
    - location: install_dependencies
      timeout: 300
  ApplicationStart:
    - location: write_codedeploy_config.sh
    - location: start_application
      timeout: 300
  ValidateService:
    - location: basic_health_check.sh
